"""
Fix users.id autoincrement behavior

This migration alters the users table so that the id column
is generated automatically. This prevents duplicate key errors
when inserting new users.

Revision ID: 20250228_fix_users_id
Revises: 20250227_add_user_columns
Create Date: 2025-02-28 12:00:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "20250228_fix_users_id"
down_revision = "20250227_add_user_columns"
branch_labels = None
depends_on = None

def upgrade() -> None:
    # For PostgreSQL 10 and later, you can alter the column to use an identity.
    op.execute("""
        ALTER TABLE users 
        ALTER COLUMN id 
        ADD GENERATED BY DEFAULT AS IDENTITY
    """)

def downgrade() -> None:
    # In downgrade, remove the identity (if supported).
    op.execute("""
        ALTER TABLE users 
        ALTER COLUMN id 
        DROP IDENTITY IF EXISTS
    """)
