#app/infrastructure/database/migrations/versions/20250228_fix_users_id.py
"""
Fix users.id autoincrement behavior with proper starting value

This migration alters the users table so that the id column is generated automatically.
It first drops any existing default and then adds identity generation with a starting value of 2,
ensuring new inserts get a unique id that doesn't conflict with existing rows.

Revision ID: 20250228_fix_users_id
Revises: 20250227_add_user_columns
Create Date: 2025-02-28 12:00:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "20250228_fix_users_id"
down_revision = "20250227_add_user_columns"
branch_labels = None
depends_on = None

def upgrade() -> None:
    # Drop any existing default on the "id" column.
    op.execute("ALTER TABLE users ALTER COLUMN id DROP DEFAULT")
    # Add identity generation with a starting value of 2.
    op.execute("ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 2)")

def downgrade() -> None:
    # Remove the identity generation.
    op.execute("ALTER TABLE users ALTER COLUMN id DROP IDENTITY IF EXISTS")
