"""
Fix users.id autoincrement behavior

This migration alters the users table so that the id column
is generated automatically via an identity. This prevents duplicate key errors
when inserting new users by ensuring new IDs are automatically assigned.

Revision ID: 20250228_fix_users_id
Revises: 20250227_add_user_columns
Create Date: 2025-02-28 12:00:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "20250228_fix_users_id"
down_revision = "20250227_add_user_columns"
branch_labels = None
depends_on = None

def upgrade() -> None:
    # Drop any existing default on the "id" column.
    op.execute("ALTER TABLE users ALTER COLUMN id DROP DEFAULT")
    # Now add identity generation so new rows get a unique id automatically.
    op.execute("ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")

def downgrade() -> None:
    # In the downgrade, remove the identity generation.
    op.execute("ALTER TABLE users ALTER COLUMN id DROP IDENTITY IF EXISTS")
    # Note: You may re-add a default manually here if needed.
