# crave_trinity_backend/app/core/use_cases/ingest_craving.py

from dataclasses import dataclass
from typing import Optional
from datetime import datetime

from app.core.entities.craving import Craving
from app.infrastructure.database.repository import CravingRepository
from app.infrastructure.external.openai_embedding import OpenAIEmbeddingService
from app.infrastructure.vector_db.vector_repository import VectorRepository


@dataclass
class IngestCravingInput:
    """DTO for ingesting a craving log."""
    user_id: int
    description: str
    intensity: int


@dataclass
class IngestCravingOutput:
    """DTO for returning a successfully saved craving."""
    id: int
    user_id: int
    description: str
    intensity: int
    created_at: datetime


def ingest_craving(input_dto: IngestCravingInput, repo: CravingRepository) -> IngestCravingOutput:
    """
    Ingest a new craving into the system.

    **Steps:**
    1. Convert the input DTO into a domain entity.
    2. Persist the entity to the database via the repository.
    3. Generate embeddings and store them in Pinecone (optional).
    4. Return an output DTO.

    :param input_dto: Craving log details.
    :param repo: Repository for database operations.
    :return: IngestCravingOutput containing saved craving details.
    """

    # ✅ Define `domain_craving` before using it
    domain_craving = Craving(
        id=None,  # Auto-generated by the DB
        user_id=input_dto.user_id,
        description=input_dto.description,
        intensity=input_dto.intensity,
        created_at=datetime.utcnow(),
    )

    # ✅ Save the craving to the database
    saved_craving = repo.create_craving(domain_craving)

    # ✅ Now optionally generate embeddings and store in Pinecone
    try:
        embed_service = OpenAIEmbeddingService()
        embedding = embed_service.embed_text(saved_craving.description)

        vector_repo = VectorRepository()
        metadata = {
            "user_id": saved_craving.user_id,
            "created_at": str(saved_craving.created_at)
        }
        vector_repo.upsert_craving_embedding(saved_craving.id, embedding, metadata)
    except Exception as e:
        # ✅ Log errors but don't crash ingestion
        print(f"Embedding error: {e}")

    # ✅ Return output DTO
    return IngestCravingOutput(
        id=saved_craving.id,
        user_id=saved_craving.user_id,
        description=saved_craving.description,
        intensity=saved_craving.intensity,
        created_at=saved_craving.created_at,
    )